name: Sync gki-android12-5.10 from simonpunk

on:
  workflow_call:

jobs:
  call-sync:
    uses: ./.github/workflows/sync-upstream.yml
    with:
      upstream_repo: https://gitlab.com/simonpunk/susfs4ksu.git
      upstream_branch: gki-android12-5.10
      local_branch: gki-android12-5.10
