name: Sync gki-android13-5.15 from simonpunk

on:
  workflow_call:

jobs:
  call-sync:
    uses: ./.github/workflows/sync-upstream.yml
    with:
      upstream_repo: https://gitlab.com/simonpunk/susfs4ksu.git
      upstream_branch: gki-android13-5.15
      local_branch: gki-android13-5.15
